# - hosts: public-daemon,private-daemon,winning-post-miner,window-post-miner,seal-miner,precommit-worker,commit-worker
- hosts: Miner
  remote_user: 'miner'
  gather_facts: no
  tasks:
    - name: miner info
      shell: "/home/miner/lotus/lotus-miner info"
      register: returnvalue
    - name: display miner info
      debug: var=returnvalue
